// <auto-generated />
using System;
using HelenSkin.Data.Access.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelenSkin.Data.Access.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240327171839_addTbToData")]
    partial class addTbToData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HelenSkin.Model.CHI_TIET_GIO_HANG", b =>
                {
                    b.Property<int>("MaCTGH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTGH"));

                    b.Property<int>("MaGioHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaCTGH");

                    b.HasIndex("MaGioHang");

                    b.HasIndex("MaSP");

                    b.ToTable("db_CHI_TIET_GIO_HANG");
                });

            modelBuilder.Entity("HelenSkin.Model.DANH_MUC", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("db_DANH_MUC");
                });

            modelBuilder.Entity("HelenSkin.Model.DON_VI_VAN_CHUYEN", b =>
                {
                    b.Property<int>("MaDonViVanChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonViVanChuyen"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenDonViVanChuyen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("MaDonViVanChuyen");

                    b.ToTable("db_DON_VI_VAN_CHUYEN");
                });

            modelBuilder.Entity("HelenSkin.Model.DS_MEDIA_HINH_ANH", b =>
                {
                    b.Property<int>("MaDSHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDSHinhAnh"));

                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<string>("MediaHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDSHinhAnh");

                    b.HasIndex("MaSP");

                    b.ToTable("db_DS_MEDIA_HINH_ANH");
                });

            modelBuilder.Entity("HelenSkin.Model.GIO_HANG", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.HasKey("MaGioHang");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("db_GIO_HANG");
                });

            modelBuilder.Entity("HelenSkin.Model.HOA_DON", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHD"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaDonViVanChuyen")
                        .HasColumnType("int");

                    b.Property<int>("MaGioHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaHD");

                    b.HasIndex("MaDonViVanChuyen");

                    b.HasIndex("MaGioHang");

                    b.ToTable("db_HOA_DON");
                });

            modelBuilder.Entity("HelenSkin.Model.NGUOI_DUNG", b =>
                {
                    b.Property<int>("MaND")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaND"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PhanQuyen")
                        .HasColumnType("bit");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenND")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaND");

                    b.ToTable("db_NGUOI_DUNG");
                });

            modelBuilder.Entity("HelenSkin.Model.SAN_PHAM", b =>
                {
                    b.Property<int>("MaSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSP"));

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaSP");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("db_SAN_PHAM");
                });

            modelBuilder.Entity("HelenSkin.Model.CHI_TIET_GIO_HANG", b =>
                {
                    b.HasOne("HelenSkin.Model.GIO_HANG", "GIO_HANG")
                        .WithMany()
                        .HasForeignKey("MaGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelenSkin.Model.SAN_PHAM", "SAN_PHAM")
                        .WithMany()
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GIO_HANG");

                    b.Navigation("SAN_PHAM");
                });

            modelBuilder.Entity("HelenSkin.Model.DS_MEDIA_HINH_ANH", b =>
                {
                    b.HasOne("HelenSkin.Model.SAN_PHAM", "SAN_PHAM")
                        .WithMany()
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SAN_PHAM");
                });

            modelBuilder.Entity("HelenSkin.Model.GIO_HANG", b =>
                {
                    b.HasOne("HelenSkin.Model.NGUOI_DUNG", "NGUOI_DUNG")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NGUOI_DUNG");
                });

            modelBuilder.Entity("HelenSkin.Model.HOA_DON", b =>
                {
                    b.HasOne("HelenSkin.Model.DON_VI_VAN_CHUYEN", "DON_VI_VAN_CHUYEN")
                        .WithMany()
                        .HasForeignKey("MaDonViVanChuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelenSkin.Model.GIO_HANG", "GIO_HANG")
                        .WithMany()
                        .HasForeignKey("MaGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DON_VI_VAN_CHUYEN");

                    b.Navigation("GIO_HANG");
                });

            modelBuilder.Entity("HelenSkin.Model.SAN_PHAM", b =>
                {
                    b.HasOne("HelenSkin.Model.DANH_MUC", "DANH_MUC")
                        .WithMany()
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DANH_MUC");
                });
#pragma warning restore 612, 618
        }
    }
}
